---
# kind: Stage
# metadata:
#   name: kflux-stg-rh01
#   annotations:
#     kargo.akuity.io/color: amber
# spec:
#   requestedFreight:
#   - origin:
#       kind: Warehouse
#       name: development
#     sources:
#       direct: true
#   promotionTemplate:
#     spec:
#       steps:
#       - task:
#           name: promote-konflux
# ---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: tekton-kueue-development
#   annotations:
#     kargo.akuity.io/color: orange
# spec:
#   requestedFreight:
#   - origin:
#       kind: Warehouse
#       name: tekton-kueue
#     sources:
#       direct: true
#   promotionTemplate:
#     spec:
#       vars:
#       - name: componentRepoURL
#         value: https://github.com/konflux-ci/tekton-kueue.git
#       - name: sourcePath
#         value: "config/default"
#       - name: kustomizationPath
#         value: konflux-ci/native/components/tekton-kueue/development/kustomization.yaml
#       steps:
#       - task:
#           name: promote-to-development


# Promotion tasks

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-stg-rh01-promote
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: development-tekton-kueue
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: outPath
        value: konflux-ci/native/components/tekton-kueue/kflux-stg-rh01/base
      - name: fromCluster
        value: development
      steps:
      - task:
          name: promote-component-with-copy

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh01-promote
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-stg-rh01-tekton-kueue
    sources:
      stages:
      - kflux-stg-rh01-deploy
  promotionTemplate:
    spec:
      vars:
      - name: fromCluster
        value: kflux-stg-rh01
      steps:
      - task:
          name: promote-component-with-copy

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh02-promote
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-prod-rh01-tekton-kueue
    sources:
      stages:
      - kflux-prod-rh01-deploy
  promotionTemplate:
    spec:
      vars:
      - name: fromCluster
        value: kflux-prod-rh01
      steps:
      - task:
          name: promote-component-with-copy

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh03-promote
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-prod-rh01-tekton-kueue
    sources:
      stages:
      - kflux-prod-rh01-deploy
  promotionTemplate:
    spec:
      vars:
      - name: fromCluster
        value: kflux-prod-rh01
      steps:
      - task:
          name: promote-component-with-copy

# Deploy tasks

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-stg-rh01-deploy
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-stg-rh01-tekton-kueue
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: deploy-cluster

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh01-deploy
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-prod-rh01-tekton-kueue
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: deploy-cluster

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh02-deploy
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-prod-rh02-tekton-kueue
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: deploy-cluster
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh03-deploy
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-prod-rh03-tekton-kueue
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: deploy-cluster

# ---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: kflux-stg-rh01-build
#   annotations:
#     kargo.akuity.io/color: amber
# spec:
#   requestedFreight:
#   - origin:
#       kind: Warehouse
#       name: kflux-stg-rh01
#     sources:
#       direct: true
#   promotionTemplate:
#     spec:
#       steps:
#       - task:
#           name: build-cluster

# ---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: kflux-prod-rh01-build
#   annotations:
#     kargo.akuity.io/color: green
# spec:
#   requestedFreight:
#   - origin:
#       kind: Warehouse
#       name: kflux-prod-rh01
#     sources:
#       direct: true
#   promotionTemplate:
#     spec:
#       steps:
#       - task:
#           name: build-cluster

# ---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: kflux-prod-rh02-build
#   annotations:
#     kargo.akuity.io/color: blue
# spec:
#   requestedFreight:
#   - origin:
#       kind: Warehouse
#       name: kflux-prod-rh02
#     sources:
#       direct: true
#   promotionTemplate:
#     spec:
#       steps:
#       - task:
#           name: build-cluster

# ---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: kflux-prod-rh03-build
#   annotations:
#     kargo.akuity.io/color: violet
# spec:
#   requestedFreight:
#   - origin:
#       kind: Warehouse
#       name: kflux-prod-rh03
#     sources:
#       direct: true
#   promotionTemplate:
#     spec:
#       steps:
#       - task:
#           name: build-cluster
