apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-stg-rh01
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: development
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-konflux

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh01
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: development
    sources:
      stages:
      - kflux-stg-rh01
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-konflux

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh02
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: development
    sources:
      stages:
      - kflux-prod-rh01
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-konflux
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh03
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: development
    sources:
      stages:
      - kflux-prod-rh01
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-konflux

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-stg-rh01-build
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-stg-rh01
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: build-cluster

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh01-build
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-prod-rh01
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: build-cluster

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh02-build
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-prod-rh02
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: build-cluster

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kflux-prod-rh03-build
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kflux-prod-rh03
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: build-cluster
