apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: konflux-ci-native
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/gbenhaim/kargo-advanced.git
